### ISSUE TITLE
Link the Spotify API for login

### ISSUE THREAD

**Issue by sbaljeet13** [ChristianChidiac/harmonIQ#5]

**Comment by mononomori** [comment]
# API references for login authentication: 


- https://github.com/spotify/web-api-examples/tree/master/authorization/authorization_code
- https://developer.spotify.com/documentation/web-api/tutorials/code-flow

**Comment by ChristianChidiac** [comment]
I deployed a Render web app that uses the Authorization Code Flow to login and authenticate with Spotify. After logging in, it displays the users’ followed artists by calling the followed artists API endpoint. Here’s the link to the render website: https://harmoniq.onrender.com/

Since the app is only in development mode, we have to add users manually so that they can use it, so the authorization won’t work for you guys unless I add your emails to the app. If you guys have Spotify accounts and want to try it I can add your Spotify account emails, but I’ll go over this web app in our next meeting.
